# Generated by Django 5.0.7 on 2024-10-14 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='florauser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='florauser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='florauser',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='florauser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='florauser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='florauser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='florauser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='florauser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='florauser',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
