# Generated by Django 5.0.7 on 2024-09-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_remove_purchasereturn_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='sales',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='journals.sales'),
        ),
    ]
