# Generated by Django 5.0.7 on 2024-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_stock_opening_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='remaining_opening_stock',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='opening_stock_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='opening_stock_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
