# Generated by Django 5.0.7 on 2024-10-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_florauser_options_alter_florauser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='florauser',
            name='username',
        ),
    ]
