# Generated by Django 5.0.7 on 2024-09-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_invoice_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='serial_number',
            field=models.CharField(default='default-001', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='serial_number',
            field=models.CharField(default='default-001', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='serial_number',
            field=models.CharField(default='default-001', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='serial_number',
            field=models.CharField(default='default-001', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='serial_number',
            field=models.CharField(default='default-001', max_length=200),
            preserve_default=False,
        ),
    ]
