# Generated by Django 5.0.7 on 2024-10-16 13:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_remove_florauser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_name', models.CharField(max_length=200)),
                ('org_email', models.EmailField(max_length=254, unique=True)),
                ('org_phone_number', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('active_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_org', to=settings.AUTH_USER_MODEL)),
                ('org_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('invite_data', models.JSONField(blank=True, null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_membership', to='journals.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
