# Generated by Django 5.0.7 on 2024-08-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_stock_remaining_opening_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='remaining_opening_stock',
        ),
    ]
