# Generated by Django 5.0.7 on 2024-10-16 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_organisation_organisationmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='active_users',
        ),
        migrations.AddField(
            model_name='florauser',
            name='current_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_users', to='journals.organisation'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
