# Generated by Django 5.0.7 on 2024-10-16 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_remove_organisation_active_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
