# Generated by Django 5.0.7 on 2024-08-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_purchase_discount_sales_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
    ]
