# Generated by Django 5.0.7 on 2024-10-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_purchasereturnentries_stock_salesreturnentries_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesentries',
            old_name='initial_quantity',
            new_name='remaining_quantity',
        ),
    ]
