# Generated by Django 5.0.7 on 2024-08-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_remove_purchase_discount_remove_sales_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales')], max_length=120)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_received', to='journals.purchase')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_allowed', to='journals.sales')),
            ],
        ),
    ]
