# Generated by Django 5.0.7 on 2024-10-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_alter_organisation_org_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='florauser',
            name='current_org',
        ),
    ]
