# Generated by Django 5.0.7 on 2024-10-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_remove_florauser_current_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='florauser',
            name='current_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_users', to='journals.organisation'),
        ),
    ]
