# Generated by Django 5.0.7 on 2024-08-30 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='account',
        ),
    ]
