# Generated by Django 5.0.7 on 2024-08-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_remove_purchase_account_remove_sales_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='purchase_id',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='sales_id',
            new_name='sales',
        ),
    ]
