# Generated by Django 5.0.7 on 2024-10-24 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0008_florauser_current_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='creator',
            field=models.ForeignKey(default='c7b7c3dc-c52b-493f-b05a-0fd328f2681f', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='organisation',
            field=models.ForeignKey(default='c7b7c3dc-c52b-493f-b05a-0fd328f2681f', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='journals.organisation'),
            preserve_default=False,
        ),
    ]
