# Generated by Django 5.0.7 on 2024-10-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_account_creator_account_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='creator',
            new_name='user',
        ),
    ]
