# Generated by Django 5.0.7 on 2024-08-30 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0009_rename_purchase_id_discount_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_received', to='journals.purchase'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='sales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount_allowed', to='journals.sales'),
        ),
    ]
