# Generated by Django 5.0.7 on 2024-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_alter_discount_purchase_alter_discount_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('capital', 'Capital'), ('expense', 'Expense'), ('income', 'Income')], default='asset', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('current_asset', 'Current Asset'), ('non_current_asset', 'Non-current Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long-term Liability'), ('owner_equity', 'Owner Equity'), ('other_equity', 'Other Equity'), ('operating_expenses', 'Operating Expenses'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('sales_revenue', 'Sales Revenue'), ('other_income', 'Other Income')], max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_category',
            field=models.CharField(choices=[('cash_and_cash_equivalents', 'Cash and Cash Equivalents'), ('accounts_receivable', 'Accounts Receivable'), ('inventory', 'Inventory'), ('prepaid_expenses', 'Prepaid Expenses'), ('property_plant_equipment', 'Property, Plant, and Equipment'), ('intangible_assets', 'Intangible Assets'), ('accounts_payable', 'Accounts Payable'), ('short_term_loans', 'Short-term Loans'), ('accrued_expenses', 'Accrued Expenses'), ('long_term_loans', 'Long-term Loans'), ('mortgage_payable', 'Mortgage Payable'), ('retained_earnings', 'Retained Earnings'), ('owner_investment', 'Owner Investment'), ('additional_contributions', 'Additional Contributions'), ('drawings', 'Drawings'), ('equity_from_loans', 'Equity from Loans'), ('subordinated_debt', 'Subordinated Debt'), ('rent_and_utilities', 'Rent and Utilities'), ('salaries_and_wages', 'Salaries and Wages'), ('marketing_and_advertising', 'Marketing and Advertising'), ('purchase_of_goods', 'Purchase of Goods'), ('freight_and_shipping', 'Freight and Shipping'), ('product_sales', 'Product Sales'), ('service_revenue', 'Service Revenue'), ('interest_income', 'Interest Income'), ('investment_income', 'Investment Income')], max_length=200),
        ),
    ]
