# Generated by Django 5.0.7 on 2024-10-26 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0010_rename_creator_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_retuns', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='purchase_retuns', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='organisation',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='journals.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='user',
            field=models.ForeignKey(default='d9d1bba9-5a8e-4daf-91c1-e952064e9595', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
