# Generated by Django 5.0.7 on 2024-08-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_account_groups_alter_account_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='groups',
            new_name='group',
        ),
    ]
