# Generated by Django 5.0.7 on 2024-10-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0011_bill_organisation_bill_user_customer_organisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesentries',
            name='cogs',
        ),
        migrations.RemoveField(
            model_name='salesreturnentries',
            name='cogs',
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('current_asset', 'Current Asset'), ('non_current_asset', 'Non-current Asset'), ('current_liability', 'Current Liability'), ('long_term_liability', 'Long-term Liability'), ('owner_equity', 'Owner Equity'), ('other_equity', 'Other Equity'), ('operating_expense', 'Operating Expense'), ('other_expense', 'Other Expense'), ('operating_income', 'Operating Income'), ('other_income', 'Other Income')], max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='sub_category',
            field=models.CharField(choices=[('cash_and_cash_equivalents', 'Cash and Cash Equivalents'), ('accounts_receivable', 'Accounts Receivable'), ('inventory', 'Inventory'), ('property_plant_equipment', 'Property, Plant, and Equipment'), ('intangible_assets', 'Intangible Assets'), ('accounts_payable', 'Accounts Payable'), ('short_term_loans', 'Short-term Loans'), ('long_term_loans', 'Long-term Loans'), ('mortgage_payable', 'Mortgage Payable'), ('retained_earnings', 'Retained Earnings'), ('owner_investment', 'Owner Investment'), ('additional_contributions', 'Additional Contributions'), ('drawings', 'Drawings'), ('equity_from_loans', 'Equity from Loans'), ('subordinated_debt', 'Subordinated Debt'), ('rent_and_utilities', 'Rent and Utilities'), ('salaries_and_wages', 'Salaries and Wages'), ('marketing_and_advertising', 'Marketing and Advertising'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('contra-revenue', 'Contra-Revenue'), ('contra-expense', 'Contra-Expense'), ('selling_expense', 'Selling Expense'), ('interent_expense', 'Interest Expense'), ('product_sales', 'Product Sales'), ('service_revenue', 'Service Revenue'), ('interest_income', 'Interest Income'), ('investment_income', 'Investment Income'), ('income_from_discounts', 'Income from Discounts')], max_length=200),
        ),
    ]
