# Generated by Django 5.0.7 on 2024-08-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0012_rename_groups_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sub_category',
            field=models.CharField(choices=[('cash_and_cash_equivalents', 'Cash and Cash Equivalents'), ('accounts_receivable', 'Accounts Receivable'), ('inventory', 'Inventory'), ('property_plant_equipment', 'Property, Plant, and Equipment'), ('intangible_assets', 'Intangible Assets'), ('accounts_payable', 'Accounts Payable'), ('short_term_loans', 'Short-term Loans'), ('long_term_loans', 'Long-term Loans'), ('mortgage_payable', 'Mortgage Payable'), ('retained_earnings', 'Retained Earnings'), ('owner_investment', 'Owner Investment'), ('additional_contributions', 'Additional Contributions'), ('drawings', 'Drawings'), ('equity_from_loans', 'Equity from Loans'), ('subordinated_debt', 'Subordinated Debt'), ('rent_and_utilities', 'Rent and Utilities'), ('salaries_and_wages', 'Salaries and Wages'), ('marketing_and_advertising', 'Marketing and Advertising'), ('cost_of_goods_sold', 'Cost of Goods Sold'), ('product_sales', 'Product Sales'), ('service_revenue', 'Service Revenue'), ('interest_income', 'Interest Income'), ('investment_income', 'Investment Income')], max_length=200),
        ),
        migrations.AlterField(
            model_name='discount',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_received', to='journals.purchase'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='sales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_allowed', to='journals.sales'),
        ),
    ]
