# Generated by Django 5.0.7 on 2024-11-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0018_serviceincome_invoice_service_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='service_income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_allowe', to='journals.serviceincome'),
        ),
        migrations.AddField(
            model_name='journalentries',
            name='service_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.serviceincome'),
        ),
        migrations.AddField(
            model_name='serviceincomeentry',
            name='service_income_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales'), ('service_income', 'Service Income')], max_length=120),
        ),
    ]
