# Generated by Django 5.0.7 on 2024-11-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0019_discount_service_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceincomeentry',
            name='service_income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_income_entries', to='journals.serviceincome'),
        ),
    ]
