# Generated by Django 5.0.7 on 2024-11-06 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0020_alter_serviceincomeentry_service_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='service_income',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_allowed', to='journals.serviceincome'),
        ),
    ]
