# Generated by Django 5.0.7 on 2024-11-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0018_alter_account_belongs_to'),
        ('journals', '0021_alter_discount_service_income'),
    ]

    operations = [
    ]
