# Generated by Django 5.0.7 on 2024-11-23 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0023_alter_bill_supplier_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='florauser',
            name='current_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='journals.organisation'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.account'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.payment'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.purchase'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='purchase_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.purchasereturn'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.sales'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.salesreturn'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='service_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='journals.serviceincome'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_membership', to='journals.organisation'),
        ),
        migrations.AlterField(
            model_name='organisationmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
