# Generated by Django 5.0.7 on 2024-11-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0025_alter_account_user_alter_bill_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='journal',
        ),
    ]
