# Generated by Django 5.0.7 on 2024-11-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0026_remove_bill_journal_remove_invoice_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentries',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.journal'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.payment'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.purchase'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='purchase_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.purchasereturn'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.sales'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='sales_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.salesreturn'),
        ),
        migrations.AlterField(
            model_name='journalentries',
            name='service_income',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='journals.serviceincome'),
        ),
    ]
