# Generated by Django 5.0.7 on 2024-11-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0027_alter_journalentries_journal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
        migrations.AddField(
            model_name='journalentries',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
