# Generated by Django 5.0.7 on 2024-11-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0028_remove_bill_organisation_remove_bill_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
    ]
