# Generated by Django 5.0.7 on 2024-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0029_remove_invoice_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
