# Generated by Django 5.0.7 on 2025-01-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0030_purchasereturn_bill_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='returns_total',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='returns_total',
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='return_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='return_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
