# Generated by Django 5.0.7 on 2025-01-22 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0031_remove_purchase_returns_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturn',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='journals.organisation'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_returns', to='journals.purchase'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_returns', to='journals.sales'),
        ),
    ]
