# Generated by Django 5.0.7 on 2025-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0034_alter_purchasereturnentries_purchase_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnentries',
            name='cogs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
