# Generated by Django 5.0.7 on 2025-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0036_rename_new_json_audittrail_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='object_id',
            field=models.UUIDField(editable=False),
        ),
    ]
