# Generated by Django 5.0.7 on 2025-01-25 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0037_alter_audittrail_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittrail',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journals.organisation'),
        ),
    ]
