# Generated by Django 6.0.5 on 2026-07-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0040_alter_subcategory_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="florauser",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organisation",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organisationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                ],
                max_length=200,
            ),
        ),
    ]
