# Generated by Django 6.0.5 on 2026-07-14 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0041_florauser_is_archived_organisation_is_archived_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="organisation", name="org_admin",),
        migrations.AddField(
            model_name="organisation",
            name="super_admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="super_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("editor", "Editor"),
                    ("viewer", "Viewer"),
                    ("super_admin", "Super Admin"),
                ],
                max_length=200,
            ),
        ),
    ]
