# Generated by Django 6.0.5 on 2026-07-21 11:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0042_remove_organisation_org_admin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("description", models.TextField()),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="journalentries",
            name="opening",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_entries",
                to="journals.opening",
            ),
        ),
    ]
