# Generated by Django 6.0.5 on 2026-07-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journals", "0043_opening_journalentries_opening"),
    ]

    operations = [
        migrations.AddField(
            model_name="opening",
            name="account",
            field=models.OneToOneField(
                default="c2a5d74c-ed03-43ed-8729-b4514316c3d5",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="journals.account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="journalentries",
            name="opening",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="journals.opening",
            ),
        ),
    ]
